#!/usr/bin/env sh
PORT=1337
COLOR=$1

nohup php -S 127.0.0.1:"$PORT" -t /opt/slowfetch/ >/dev/null 2>&1 &

if [ "$COLOR" = "" ]; then
  if [ -f "$HOME/.config/slowfetch.txt" ]; then
    COLOR=$(cat "$HOME/.config/slowfetch.txt")
  fi
fi

if [ "$1" = "set" ]; then
  if [ "$2" = "reset" ]; then
    echo "" > "$HOME/.config/slowfetch.txt"
    exit
  fi
  echo "$2" > "$HOME/.config/slowfetch.txt"
  exit
fi

if [ $# -eq 0 ] && [ "$COLOR" = "" ]; then
  until curl -s localhost:"$PORT"; do
  sleep 0.1
  done
  else
  until curl -s localhost:"$PORT"?color="$COLOR"; do
  sleep 0.1
  done
fi

PHPPID="$(pidof php)"
kill "$PHPPID"